version: "1.0"
name: "comfyui"
description: "免费算力平台安装comfyui"
install:
  environments:
    base:
      pip_index: "https://pypi.tuna.tsinghua.edu.cn/simple"
      pip_timeout: 300
      pip_retries: 3
      base_dir: "/workspace"
      python_cmd: "python"
      use_sudo: false
      env_vars: {}
      packages: []
      system_packages: []
      venv_dir: "venv_confyui"
      app_repo: "https://openi.pcl.ac.cn/niubi/ComfyUI.git"
      python_ver: "3.12.9"
      repo_name: "ComfyUI"
      custom_node_1: "comfyui-manager"
      custom_node_1_repo: "https://openi.pcl.ac.cn/niubi/comfyui-manager.git"
      info_url: "https://fuliai-ai2u.hf.space/"
      ksa_repo: "https://gitee.com/fuliai/ai2u.git"
  steps:
    - name: "安装前准备"
      description: "系统依赖"
      common:
        - |
          apt-get update && \
          apt install -y \
            build-essential \
            libgl1 \
            ffmpeg \
            python3-pip \
            aria2 \
            git \
            git-lfs \
            htop

        - "pip install uv -i {pip_index}"

    - name: "代码管理"
      description: "获取应用程序代码"
      common:
        - |
          cd {base_dir} && \
          if [ -d "{repo_name}" ]; then
            echo "更新仓库..." && \
            cd {repo_name} && \
            git pull
          else
            echo "克隆仓库..." && \
            git clone {app_repo} {repo_name} && \
            cd {repo_name}
          fi

    - name: "虚拟环境"
      description: "检测并创建虚拟环境"
      common:
        - "uv venv {base_dir}/{venv_dir} --python={python_ver}"
        - |
          . {base_dir}/{venv_dir}/bin/activate && \
          which python && \
          uv pip install -U pip -i {pip_index} && \
          uv pip install -U \
            aria2 \
            insightface \
            "numpy<2.0" \
            -i {pip_index} && \
          uv pip install -r {base_dir}/{repo_name}/requirements.txt -i {pip_index}

    - name: "安装自定义插件"
      description: "安装额外功能模块"
      common:
        - |
          . {base_dir}/{venv_dir}/bin/activate && \
          cd {base_dir}/{repo_name}/custom_nodes && \
          if [ -d "{custom_node_1}" ]; then
            echo "更新插件仓库..." && \
            cd {custom_node_1} && \
            git pull
          else
            echo "克隆插件仓库..." && \
            git clone {custom_node_1_repo} {custom_node_1} && \
            cd {custom_node_1}
          fi && \
          uv pip install -r requirements.txt -i {pip_index}

    - name: "部署KSA内网穿透"
      description: "一键安装并运行KSA"
      common:
        - |
          # 下载和解压
          mkdir -p {base_dir}/ksa && \
          if [ -d "ai2u" ]; then
            echo "更新仓库..." && \
            cd ai2u && \
            git pull
          else
            echo "克隆仓库..." && \
            git clone {ksa_repo} && \
            cd ai2u
          fi
          unzip -o ksa.zip -d {base_dir}/ && \
          chmod +x {base_dir}/ksa/ksa_x64

          # 清理旧文件并运行
          rm -f {base_dir}/ksa_ID_Token.txt && \
          echo "正在启动 KSA..." && \
          {base_dir}/ksa/ksa_x64 > {base_dir}/ksa_ID_Token.txt 2>&1

          # 检查文件内容是否有指定内容：“KSA ID”，来确定是否运行成功
          if grep -q "KSA ID" {base_dir}/ksa_ID_Token.txt; then
            echo "KSA 运行成功"
          else
            echo "KSA 运行失败"
            {base_dir}/ksa/ksa_x64 > {base_dir}/ksa_ID_Token.txt 2>&1
          fi

    - name: "生成相关文件并进行提示"
      description: "创建详细指南" 
      common:
        - |
          mkdir -p {base_dir} && \
          cat << EOF > {base_dir}/{repo_name}使用说明.txt
          ========== {repo_name} 使用说明 ==========
          启动 {repo_name} 命令：
          （在终端中输入并运行）
          cd {base_dir}/ksa/ && ./ksa_x64
          source {base_dir}/{venv_dir}/bin/activate
          export HF_ENDPOINT=https://hf-mirror.com
          python {base_dir}/{repo_name}/main.py
          
          启动后，使用ksa客户端连接，账号密码在{base_dir}/ksa_ID_Token.txt 中。
          连接成功后请在浏览器中访问：
          http://10.0.0.1:8188
          
          停止 {repo_name} 命令：
          直接 ctrl+c 停止,或者
          （在终端中输入并运行）
          pkill -f "python main.py"

          查看最新的命令：
          请查看 https://fuliai-ai2u.hf.space/

          内网穿透：
          请查看视频教程来了解如何使用：https://www.bilibili.com/video/BV1VENaeUEDf/
          
          查看最新的相关说明：
          请查看 https://fuliai-ai2u.hf.space/
          加群交流：https://qr61.cn/oohivs/qRp62U6

          如果需要更新，请重新运行一键安装命令，就会更新comfyui
          如果需要手动安装自定义插件，请在虚拟环境中运行：
          cd {base_dir}/{repo_name}/custom_nodes
          git clone 插件仓库地址
          cd 插件名称
          #启动虚拟环境
          . {base_dir}/{venv_dir}/bin/activate
          #安装插件依赖
          uv pip install -r requirements.txt -i {pip_index}
          
          安装日志查看：
          请查看 {base_dir}/aiinstall/logs/ 中的各安装日志
          EOF

        - "chmod 644 {base_dir}/{repo_name}使用说明.txt"
        