version: "1.0"
name: "comfyui"
description: "免费算力平台安装comfyui"
install:
  environments:
    base:
      pip_index: "https://pypi.tuna.tsinghua.edu.cn/simple"
      pip_timeout: 300
      pip_retries: 3
      base_dir: "/workspace"
      python_cmd: "python"
      use_sudo: false
      env_vars: {}
      packages: []
      system_packages: []
      venv_dir: "venv_confyui"
      app_repo: "https://openi.pcl.ac.cn/niubi/ComfyUI.git"
      python_ver: "3.12.9"
      repo_name: "ComfyUI"
  steps:
    - name: "安装前准备"
      description: "系统依赖"
      common:
        - |
          apt-get update && \
          apt install -y \
            build-essential \
            libgl1 \
            ffmpeg \
            python3-pip \
            aria2 \
            git \
            git-lfs \
            htop

        - "pip install uv -i {pip_index}"

    - name: "代码管理"
      description: "获取应用程序代码"
      common:
        - |
          cd {base_dir} && \
          if [ -d "{repo_name}" ]; then
            echo "更新仓库..." && \
            cd {repo_name} && \
            git pull
          else
            echo "克隆仓库..." && \
            git clone {app_repo} {repo_name} && \
            cd {repo_name}
          fi

    - name: "虚拟环境"
      description: "检测并创建虚拟环境"
      common:
        - "uv venv {base_dir}/{venv_dir} --python={python_ver}"
        - |
          . {base_dir}/{venv_dir}/bin/activate && \
          which python && \
          uv pip install -U pip -i {pip_index} && \
          uv pip install -U \
            aria2 \
            insightface \
            "numpy<2.0" \
            -i {pip_index} && \
          uv pip install -r {base_dir}/{repo_name}/requirements.txt -i {pip_index}
