# demo.yml - 最小化测试配置
version: "1.0"
name: "test-app"
description: "验证安装程序基本功能"

# 使用预设环境
environment: "ubuntu-a"  # 指定使用的环境配置

# 安装步骤
steps:
  - name: "test-basic"
    description: "测试基本命令执行"
    common:
      - "mkdir -p {base_dir}"
      - "echo 'Test in {base_dir}' > {base_dir}/test.txt"
      - "cat {base_dir}/test.txt"

  - name: "test-python"
    description: "测试Python环境"
    common:
      - "{python_cmd} -c 'print(\"Python works!\")'" 