# 预设环境配置
version: "1.0"

environments:
  # 基础环境配置
  base: &env-base
    python_cmd: "python3"
    pip_index: "https://pypi.org/simple"
    pip_timeout: 60
    pip_retries: 3

  # 非sudo环境
  ubuntu-a: &ubuntu-a
    <<: *env-base
    base_dir: "/home/{user}/ai_apps/{name}"
    use_sudo: false
    env_vars:
      PYTHONPATH: "{base_dir}/src"
    
  github: &github
    <<: *env-base
    base_dir: "/workspace"
    use_sudo: false

  # sudo环境
  ubuntu-b: &ubuntu-b
    <<: *env-base
    base_dir: "/opt/ai/{name}"
    use_sudo: true
    env_vars:
      PYTHONPATH: "{base_dir}/src"

  # 中国区环境
  ubuntu-a-cn:
    <<: *ubuntu-a
    pip_index: "https://pypi.tuna.tsinghua.edu.cn/simple"

  ubuntu-b-cn:
    <<: *ubuntu-b
    pip_index: "https://pypi.tuna.tsinghua.edu.cn/simple" 